config/routes.rb
Jogger::Application.routes.draw do
  devise_for :people

  root "home#index"

  post 'journals/:journal_id/entries/new' => 'entries#create'
  post 'journals/:journal_id/entries/:id' => 'entries#show'

  get 'journals/:has_taggables_id/entries/tags/:tag' => 'entries#by_tag', as: "entry_tag_search"
  get 'tasks/tags/:tag' => 'tasks#by_tag', as: "task_tag_search"

  resources :journals do
    resources :entries
  end

  resources :tasks
  
  resources :tags

  resources :uploads

  resources :audio_clips
  resources :video_clips
  resources :photographs

end

app/models/audio_clip.rb
class AudioClip < Memory
  
  def folder; "audio_clip"; end
end

app/models/carer.rb
class Carer < Person
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :person

  validates_presence_of :body
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :favourable, polymorphic: true
  belongs_to :person
end

app/models/file_upload.rb
class FileUpload < ActiveRecord::Base

  # Accepts ActionDispatch::Http::UploadedFile
  def self.create_from_params(upload)
    new.tap do |file|
      file.name = "#{hashing}#{File.extname(upload.original_filename)}"
      file.path = "/uploads/memories/#{file.name}"
      file.size = upload.tempfile.size

      file.save

      File.open(
        Rails.root.join('public', 'uploads', 'memories', file.name), 'wb'
      ) do |save_file| 
        save_file.write(upload.read)
      end
    end
  end

  private

    def self.hashing
      Digest::MD5.hexdigest("#{Time.now}")
    end

end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :entries, class_name: "JournalEntry"
  belongs_to :person

  def self.find_by_tag_title(title)
    joins(:tags).where("tags.title = ?", title)
  end
end

app/models/memory.rb
class Memory < ActiveRecord::Base
  has_many :attaches_memories, as: :memory

  belongs_to :file, class_name: "FileUpload"
  has_many :comments, as: :commentable
  has_many :favourites, as: :favourable

  def hosted_externally?
    not uploaded
  end

  def tag
    return :audio_tag if self.class.name == "AudioClip"
    return :video_tag if self.class.name == "VideoClip"
    return :image_tag if self.class.name == "Photograph"
  end

  def file_path
    "/memories/#{folder}/#{filename}"
  end

  def attached_to(type)
    attaches_memories.where("has_attachment_type = ?", String(type).camelize).map {|am| am.has_attachment }
  end

  def self.where_attached_to(model)
    AttachesMemory.where(has_attachment: model)
  end

  def delete
    File.delete(Rails.root.join("public", "uploads", "memories", file.name))
    super
  end

  def folder; "memory"; end
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :memories
  has_many :favourites

  def self.types
    ["User", "Carer"]
  end

  def is? a_type
    type.downcase == String(a_type).downcase
  end
end

app/models/photograph.rb
class Photograph < Memory

  def folder; "photograph"; end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :person
  has_many :tasks
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings

  validates_presence_of :title
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base

  belongs_to :taggable, polymorphic: true
  belongs_to :tag

  def self.parse(tags)
    tags.strip.split(",").map {|t| new(tag: Tag.find_or_create_by(title: t)) }
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  has_many :attaches_memories, as: :has_attachment
  has_many :memories, through: :attaches_memories, source_type: "Memory"

  validates_presence_of :details

  def self.find_by_tag(title)
    joins(:tags).where("tags.title = ?", title)
  end

  def attach_many(ids)
    AttachesMemory.attach_to(self, ids)
  end

  def attach(memory)
    AttachesMemory.find_or_create_by(has_attachment: self, memory: memory)
  end
end

app/models/user.rb
class User < Person
  has_many :journals, foreign_key: :person_id
  has_many :journal_entries
  has_many :tasks
  has_many :audio_clips, foreign_key: :person_id
  has_many :video_clips, foreign_key: :person_id
  has_many :photographs, foreign_key: :person_id
end

app/models/video_clip.rb
class VideoClip < Memory

  def folder; "video_clip"; end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def show
    @entry = current_person.journal_entries.find(params[:id])
  end

  def by_tag 
    @tag = params[:tag]

    @entries = current_person
      .journals
      .find(params[:has_taggables_id])
      .entries
      .joins(:tags)
      .where("tags.title = ?", @tag)

    rescue
      redirect_to controller: :home, action: :index, flash: { error: "No entries with this tag" }
  end

  def new
    @journal = Journal.find(params[:journal_id])
    @entry = JournalEntry.new(journal: @journal)
  end

  def create
    @entry = JournalEntry.new(entry_params)
    @entry.taggings = Tagging.parse(params[:tags])

    if @entry.save
      unless params[:attachment].nil?
        AttachmentAdder.new(@entry).attach_many(params[:attachment].map{|id, _| id.to_i })
      end

      flash[:notice] = "Successfully created a new Journal Entry"
      redirect_to @entry.journal
    else
      flash[:error] = "There were some problems creating your new Journal Entry"
      render :new
    end
  end

  def update
    @entry = current_person.journal_entries.find(params[:id])
    @entry.update_attributes(entry_params)

    if @entry.save
      unless params[:attachment].nil?
        AttachmentAdder.new(@entry).attach_many(params[:attachment].map{|id, _| id.to_i })
      end
      
      flash[:notice] = "Successfully updated your Journal Entry"
      redirect_to @entry.journal
    else
      flash[:error] = "There were some problems updating your Journal Entry"
      render :show
    end
  end

  private

    def entry_params
      params.require(:journal_entry).permit(:body, :journal_id)
    end

end

app/helpers/audio_helper.rb
module AudioHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_complete_btn_class(complete)
    "btn " << (complete ? "btn-default active" : "btn-success")
  end
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/entries/_index.html.erb
<% entries.each do |entry| %>
  <div class="panel panel-default panel-flat">
    <div class="panel-heading">
      Written: <%= entry.created_at.to_formatted_s(:long) %>
    </div>
    <div class="panel-body">
      <div class="reading">
        <%= simple_format(entry.body) %>
      </div>

      <% if entry.tags.any? %>
        <div class="tags">
          <strong>Tags:</strong>    
          <% entry.tags.each do |tag| %>
            <%= link_to(tag.title, entry_tag_search_path(tag: tag.title, has_taggables_id: entry.taggable.id)) %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <%= render 'memories/display', memories: entry.memories %>
<% end %>

<% unless entries.any? %>
  <p class="center">No entries in this journal, why not write one?</p>
<% end %>

app/views/entries/_new.html.erb
<div class="panel panel-success panel-flat">
  <div class="panel-heading">
    <h3 class="panel-title">New Entry</h3>
  </div>
  <div class="panel-body">
    <%= form_for(JournalEntry.new, url: new_journal_entry_path(journal)) do |f| %>
      <div class="form-group">
        <%= f.text_area(:body, class: "form-control input-lg input-body") %>
      </div>

      <div class="form-gorup">
        <label>Add a Photo, Sound or Video</label>
        <div class="scrollable well">
            <%= render 'memories/choose', memories: current_person.memories, attachable: JournalEntry.new %>
        </div>
      </div>

      <div class="form-group form-inline">
        <%= f.label("Tags") %>
        <%= text_field_tag(:tags, "", class: "form-control") %> 
        <p class="help-block">Seperate your tags with a comma. e.g.: kids, friends, dog</p>
      </div>
      <div class="form-group">
        <%= f.hidden_field(:journal_id, value: journal.id) %>
        <%= f.submit("Post", class: "btn btn-primary") %>
      </div>
    <% end %>
  </div>
</div>

app/views/entries/by_tag.html.erb
<h1>Entries with tag: <%= @tag %></h1>

<%= render 'index', entries: @entries %>

app/views/entries/index.html.erb
<%= render 'index', entries: @entries %>

app/views/entries/new.html.erb
<%= render 'new', journal: @journal %>

<div class="panel panel-flat">
  <div class="panel-body">
    <p class="center">
      <%= link_to("View all entries in this journal", journal_path(@journal)) %>
    </p>
  </div>
</div>

app/views/entries/show.html.erb
show