config/routes.rb
Jogger::Application.routes.draw do
  devise_for :people

  root "home#index"

  post 'journals/:journal_id/entries/new' => 'entries#create'
  post 'journals/:journal_id/entries/:id' => 'entries#show'

  get 'journals/:has_taggables_id/entries/tags/:tag' => 'entries#by_tag', as: "entry_tag_search"
  get 'tasks/tags/:tag' => 'tasks#by_tag', as: "task_tag_search"

  resources :journals do
    resources :entries
  end

  resources :tasks
  
  resources :tags

  resources :uploads

  resources :audio_clips
  resources :video_clips
  resources :photographs

end

app/models/audio_clip.rb
class AudioClip < Memory
  
  def folder; "audio_clip"; end
end

app/models/carer.rb
class Carer < Person
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :person

  validates_presence_of :body
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :favourable, polymorphic: true
  belongs_to :person
end

app/models/file_upload.rb
class FileUpload < ActiveRecord::Base

  # Accepts ActionDispatch::Http::UploadedFile
  def self.create_from_params(upload)
    new.tap do |file|
      file.name = "#{hashing}#{File.extname(upload.original_filename)}"
      file.path = "/uploads/memories/#{file.name}"
      file.size = upload.tempfile.size

      file.save

      File.open(
        Rails.root.join('public', 'uploads', 'memories', file.name), 'wb'
      ) do |save_file| 
        save_file.write(upload.read)
      end
    end
  end

  private

    def self.hashing
      Digest::MD5.hexdigest("#{Time.now}")
    end

end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :entries, class_name: "JournalEntry"
  belongs_to :person

  def self.find_by_tag_title(title)
    joins(:tags).where("tags.title = ?", title)
  end
end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  belongs_to :journal
  
  has_many :attaches_memories, as: :has_attachment
  has_many :memories, through: :attaches_memories, source_type: "Memory"
  
  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  validates_presence_of :body

  def self.find_by_tag(title)
    joins(:tags).where("tags.title = ?", title)
  end

  def taggable
    journal
  end

  def attach(memory)
    AttachesMemory.create(has_attachment: self, memory: memory)
  end
end

app/models/memory.rb
class Memory < ActiveRecord::Base
  has_many :attaches_memories, as: :memory

  belongs_to :file, class_name: "FileUpload"
  has_many :comments, as: :commentable
  has_many :favourites, as: :favourable

  def hosted_externally?
    not uploaded
  end

  def tag
    return :audio_tag if self.class.name == "AudioClip"
    return :video_tag if self.class.name == "VideoClip"
    return :image_tag if self.class.name == "Photograph"
  end

  def file_path
    "/memories/#{folder}/#{filename}"
  end

  def attached_to(type)
    attaches_memories.where("has_attachment_type = ?", String(type).camelize).map {|am| am.has_attachment }
  end

  def self.where_attached_to(model)
    AttachesMemory.where(has_attachment: model)
  end

  def delete
    File.delete(Rails.root.join("public", "uploads", "memories", file.name))
    super
  end

  def folder; "memory"; end
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :memories
  has_many :favourites

  def self.types
    ["User", "Carer"]
  end

  def is? a_type
    type.downcase == String(a_type).downcase
  end
end

app/models/photograph.rb
class Photograph < Memory

  def folder; "photograph"; end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :person
  has_many :tasks
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings

  validates_presence_of :title
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base

  belongs_to :taggable, polymorphic: true
  belongs_to :tag

  def self.parse(tags)
    tags.strip.split(",").map {|t| new(tag: Tag.find_or_create_by(title: t)) }
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  has_many :attaches_memories, as: :has_attachment
  has_many :memories, through: :attaches_memories, source_type: "Memory"

  validates_presence_of :details

  def self.find_by_tag(title)
    joins(:tags).where("tags.title = ?", title)
  end

  def attach_many(ids)
    AttachesMemory.attach_to(self, ids)
  end

  def attach(memory)
    AttachesMemory.find_or_create_by(has_attachment: self, memory: memory)
  end
end

app/models/user.rb
class User < Person
  has_many :journals, foreign_key: :person_id
  has_many :journal_entries
  has_many :tasks
  has_many :audio_clips, foreign_key: :person_id
  has_many :video_clips, foreign_key: :person_id
  has_many :photographs, foreign_key: :person_id
end

app/models/video_clip.rb
class VideoClip < Memory

  def folder; "video_clip"; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = current_person.tasks.new
  end

  def create
    @task = current_person.tasks.new(task_params)
    @task.taggings = Tagging.parse(params[:tags])

    if @task.save
      unless params[:attachment].nil?
        AttachmentAdder.new(@task).attach_many(params[:attachment].map{|id, _| id.to_i })
      end
      
      flash[:notice] = "Successfully created a new Task"
      redirect_to tasks_path
    else
      flash[:error] = "There were some problems creating your new Task"
      render :new
    end
  end

  def index
    @tasks = current_person.tasks
  end

  def show
    @task = current_person.tasks.find(params[:id])
  end

  def by_tag
    @tasks = current_person.tasks.joins(:taggings, :tags).where("tags.title = ?", params[:tag]).uniq
    render :index
  end

  def update
    @task = current_person.tasks.find(params[:id])
    @task.update_attributes(task_params)

    if @task.save
      unless params[:attachment].nil?
        AttachmentAdder.new(@task).attach_many(params[:attachment].map{|id, _| id.to_i })
      end
      
      redirect_to :back, flash: { notice: "Successfully Updated Task" }
    else
      redirect_to :back, flash: { error: "Could not update Task!" }
    end
  end

  private

    def task_params
      params.require(:task).permit(:due, :details, :tags, :complete)
    end

end

app/helpers/audio_helper.rb
module AudioHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_complete_btn_class(complete)
    "btn " << (complete ? "btn-default active" : "btn-success")
  end
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/tasks/_new.html.erb
<div class="panel panel-success panel-flat">
  <div class="panel-heading">
    <h3 class="panel-title">New Task</h3>
  </div>
  
  <%= form_for(task) do |f| %>
    <div class="panel-body">
      <div class="form-group">
        <%= f.label(:details, "Task Details") %>
        <%= f.text_area(:details, class: "form-control input-lg input-body") %>
        <p class="help-block">Describe what you need to do</p>
      </div>
      <div class="form-group">
        <%= f.label(:due) %>
        <%= f.datetime_select(:due, class: "form-control") %>
      </div>

      <div class="form-gorup">
        <label>Add a Photo, Sound or Video</label>
        
        <div class="scrollable well">
          <%= render 'memories/choose', memories: current_person.memories, attachable: task %>
        </div>
      </div>

      <div class="form-group form-inline">
        <%= f.label("Tags") %>
        <%= text_field_tag(:tags, "", class: "form-control") %> 
        <p class="help-block">Seperate your tags with a comma. e.g.: kids, friends, dog</p>
      </div>
    </div>
    <div class="panel-footer">
      <%= f.submit("Create Task", class: "btn btn-primary") %>
    </div>
  <% end %>
</div>

app/views/tasks/_overview.html.erb
<div class="panel panel-default panel-flat">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= glyphicon("calendar") %> Tasks
      <span class="right">
        <%= link_to(glyphicon("plus") << " New Task", new_task_path(user: current_person)) %>
      </span>
    </h3>
  </div>

  <% unless user.tasks.any? %>
    <div class="panel-body">
      <p class="center reading">No Tasks! Why not click "New Task" and get started.</p>
    </div>
  <% end %>

<% if user.tasks.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th style="width: 15%">Mark Done</th>
        <th>Description</th>
        <th style="width: 15%">View</th>
      </tr>
    </thead>
    <% user.tasks.each do |task| %>
      <tr>
        <td class="center">
          <%= form_for(task) do |f| %>
            <%= f.hidden_field(:complete, value: !task.complete) %>
            <button class="<%= task_complete_btn_class(task.complete) %>"><%= glyphicon("ok") %></button>
          <% end %>
        </td>
        <td class="reading"><%= truncate(task.details, length: 50) %></td>
        <td><%= link_to(glyphicon("arrow-right"), task, class: "btn btn-info") %></td>
    <% end %>
  </table>
<% end %>

<% if user.tasks.any? %>
  <div class="panel-footer">
    <p><%= link_to("View all Tasks", tasks_path, class: "btn btn-primary") %></p>
  </div>
<% end %>
</div>

app/views/tasks/index.html.erb
<h3 class="center">Your Tasks</h3>

<% @tasks.each do |task| %>

  <div class="panel panel-default panel-flat">
    <div class="panel-heading">
      <span class="right">
        <%= link_to("View", task) %>
      </span>
      <h3 class="panel-title">
        Due <%= task.due.to_formatted_s(:long) %>
      </h3>
    </div>
    <div class="panel-body">
      <div class="reading">
        <%= simple_format(task.details) %>
      </div>

      <% if task.tags.any? %>
        <div class="tags">
          <strong>Tags:</strong>    
          <% task.tags.each do |tag| %>
            <%= link_to(tag.title, task_tag_search_path(tag: tag.title)) %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <%= render 'memories/display', memories: task.memories %>

<% end %>

<%= render 'new', task: Task.new %>

app/views/tasks/new.html.erb
<%= render 'new', task: @task %>

app/views/tasks/show.html.erb
<%= form_for(@task, html: { class: "form-horizontal" }) do |f| %>
  <div class="panel panel-default panel-flat" id="details-edit">
    <div class="panel-heading">
      <h3 class="panel-title">Edit Task Description</h3>
    </div>

    <div class="panel-body">
      <%= f.text_area(:details, class: "form-control input-lg") %>
    </div>

    <div class="panel-footer">
      <%= f.submit("Update Task", class: "btn btn-primary", id: "update-description") %>
    </div>
  </div>

  <div class="panel panel-default panel-flat" id="details-view">
    <div class="panel-heading">
      <h3 class="panel-title">Task Description</h3>
    </div>

    <div class="panel-body">
      <div class="reading">
        <%= simple_format(@task.details) %>
      </div>
    </div>

    <div class="panel-footer">
      <button class="btn btn-info" id="edit-task-button">Edit Task Description</button>
    </div>
  </div>

  <%= render 'memories/display', memories: @task.memories %>

  <div class="panel panel-default panel-flat">
    <div class="panel-heading">
      <h3 class="panel-title">Task Details</h3>
    </div>

    <div class="panel-body">   
      <div class="form-group">
        <%= f.label(:created_at, class: "control-label col-md-2") %>
        <div class="col-md-10">
          <%= @task.created_at.to_formatted_s(:long) %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label(:due, "Task Due", class: "control-label col-md-2") %>
        <div class="col-md-10">
          <%= f.datetime_select(:due) %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label(:complete, "Task Completed?", class: "control-label col-md-2") %>
        <div class="col-md-10">
          <%= f.check_box(:complete) %>
        </div>
      </div>

      <div class="form-gorup">
        <label>Add a Photo, Sound or Video</label>
        
        <div class="scrollable well">
          <%= render 'memories/choose', memories: current_person.memories, attachable: @task %>
        </div>
      </div>
    </div>

    <div class="panel-footer">
      <%= f.submit("Update Task", class: "btn btn-primary", id: "normal-submit") %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  
var updateDescriptionButton = $("#update-description");
var editTaskButton = $('#edit-task-button');
var normalSubmitButton = $("#normal-submit");
var detailsEdit = $("#details-edit").hide();
var detailsView = $("#details-view").show();

$('form').on('submit', function(){ 
  return confirm("This will save all changes on this page, Do you wish to continue?"); 
});

editTaskButton.on("click", function(e){
  e.preventDefault();
  detailsView.toggle();
  detailsEdit.toggle();
  return false;
});

</script>