config/routes.rb
Jogger::Application.routes.draw do
  devise_for :people

  root "home#index"

  post 'journals/:journal_id/entries/new' => 'entries#create'
  post 'journals/:journal_id/entries/:id' => 'entries#show'

  get 'journals/:has_taggables_id/entries/tags/:tag' => 'entries#by_tag', as: "entry_tag_search"
  get 'tasks/tags/:tag' => 'tasks#by_tag', as: "task_tag_search"

  resources :journals do
    resources :entries
  end

  resources :tasks
  
  resources :tags

  resources :uploads

  resources :audio_clips
  resources :video_clips
  resources :photographs

end

app/models/audio_clip.rb
class AudioClip < Memory
  
  def folder; "audio_clip"; end
end

app/models/carer.rb
class Carer < Person
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :person

  validates_presence_of :body
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :favourable, polymorphic: true
  belongs_to :person
end

app/models/file_upload.rb
class FileUpload < ActiveRecord::Base

  # Accepts ActionDispatch::Http::UploadedFile
  def self.create_from_params(upload)
    new.tap do |file|
      file.name = "#{hashing}#{File.extname(upload.original_filename)}"
      file.path = "/uploads/memories/#{file.name}"
      file.size = upload.tempfile.size

      file.save

      File.open(
        Rails.root.join('public', 'uploads', 'memories', file.name), 'wb'
      ) do |save_file| 
        save_file.write(upload.read)
      end
    end
  end

  private

    def self.hashing
      Digest::MD5.hexdigest("#{Time.now}")
    end

end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :entries, class_name: "JournalEntry"
  belongs_to :person

  def self.find_by_tag_title(title)
    joins(:tags).where("tags.title = ?", title)
  end
end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  belongs_to :journal
  
  has_many :attaches_memories, as: :has_attachment
  has_many :memories, through: :attaches_memories, source_type: "Memory"
  
  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  validates_presence_of :body

  def self.find_by_tag(title)
    joins(:tags).where("tags.title = ?", title)
  end

  def taggable
    journal
  end

  def attach(memory)
    AttachesMemory.create(has_attachment: self, memory: memory)
  end
end

app/models/memory.rb
class Memory < ActiveRecord::Base
  has_many :attaches_memories, as: :memory

  belongs_to :file, class_name: "FileUpload"
  has_many :comments, as: :commentable
  has_many :favourites, as: :favourable

  def hosted_externally?
    not uploaded
  end

  def tag
    return :audio_tag if self.class.name == "AudioClip"
    return :video_tag if self.class.name == "VideoClip"
    return :image_tag if self.class.name == "Photograph"
  end

  def file_path
    "/memories/#{folder}/#{filename}"
  end

  def attached_to(type)
    attaches_memories.where("has_attachment_type = ?", String(type).camelize).map {|am| am.has_attachment }
  end

  def self.where_attached_to(model)
    AttachesMemory.where(has_attachment: model)
  end

  def delete
    File.delete(Rails.root.join("public", "uploads", "memories", file.name))
    super
  end

  def folder; "memory"; end
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :memories
  has_many :favourites

  def self.types
    ["User", "Carer"]
  end

  def is? a_type
    type.downcase == String(a_type).downcase
  end
end

app/models/photograph.rb
class Photograph < Memory

  def folder; "photograph"; end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :person
  has_many :tasks
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings

  validates_presence_of :title
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base

  belongs_to :taggable, polymorphic: true
  belongs_to :tag

  def self.parse(tags)
    tags.strip.split(",").map {|t| new(tag: Tag.find_or_create_by(title: t)) }
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  has_many :attaches_memories, as: :has_attachment
  has_many :memories, through: :attaches_memories, source_type: "Memory"

  validates_presence_of :details

  def self.find_by_tag(title)
    joins(:tags).where("tags.title = ?", title)
  end

  def attach_many(ids)
    AttachesMemory.attach_to(self, ids)
  end

  def attach(memory)
    AttachesMemory.find_or_create_by(has_attachment: self, memory: memory)
  end
end

app/models/user.rb
class User < Person
  has_many :journals, foreign_key: :person_id
  has_many :journal_entries
  has_many :tasks
  has_many :audio_clips, foreign_key: :person_id
  has_many :video_clips, foreign_key: :person_id
  has_many :photographs, foreign_key: :person_id
end

app/models/video_clip.rb
class VideoClip < Memory

  def folder; "video_clip"; end
end

app/controllers/photographs_controller.rb
class PhotographsController < ApplicationController

  def create
    @file = FileUpload.create_from_params(params[:photograph][:file])
    @photograph = current_person.photographs.new(file: @file)
    if @photograph.save
      redirect_to :back, flash: { notice: "Successfully Saved Photograph" }
    else
      redirect_to :back, flash: { error: "Could not save Photograph!" }
    end
  end

  def index
    @photographs = current_person.photographs
  end

  def destroy
    @photograph = current_person.photographs.find(params[:id])

    if @photograph.delete 
      redirect_to :back, flash: { notice: "Successfully Deleted photograph" }
    else
      redirect_to :back, flash: { error: "Could not delete photograph!" }
    end
  end

end

app/helpers/audio_helper.rb
module AudioHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_complete_btn_class(complete)
    "btn " << (complete ? "btn-default active" : "btn-success")
  end
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/photographs/_new.html.erb
<div class="panel panel-default panel-flat">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= glyphicon("camera") %> Photographs
      <span class="right">
        <%= link_to("View All", photographs_path) %>
      </span>
    </h3>
  </div>

  <div class="panel-body">
    <%= form_for(Photograph.new) do |f| %>
      <%= f.file_field(:file, id: "camera-button-input", accept: "image/*", capture: "camera") %>
      
      <a href="#" class="thumbnail" id="camera-thumbnail-link">
        <img id="camera-image-preview" src="http://placehold.it/350x150&text=Take+a+photo">
      </a>

      <div class="center">
        <a href="#" id="camera-button" class="btn btn-success btn-lg">
          <%= glyphicon("camera") %> Take Photo
        </a>
        <%= f.submit("Save", id: "camera-button-sumbit", class: "btn btn-primary btn-lg") %>
      </div>
    <% end %>
  </div>
</div>

app/views/photographs/index.html.erb
<h3 class="center">Your Photos</h3>


<% @photographs.each_slice(3) do |slice| %>
  <div class="row">
    <% slice.each do |photo| %>
      <div class="col-md-4 col-sm-4">
        <div class="thumbnail">
          <%= link_to(image_tag(photo.file.path, class: "only-fill"), photo.file.path) %>

          <div class="caption">
            <p>
              Uploaded <%= photo.created_at.to_formatted_s(:long) %>
              <%= link_to("Delete", photograph_path(photo), method: :delete, data: { confirm: "Are you certain you wish to delete this Clip?" }, class: "btn btn-sm btn-danger") %>
            </p>

            <% if photo.attaches_memories.any? %>
              <% %i(journal_entry, task).each do |attachable| %>
                <% if photo.attached_to(attachable).any? %>
                  <p><strong><%= attachable.to_s.humanize.pluralize.capitalize %></strong></p>
                  <ol>
                    <% photo.attached_to(attachable).each do |has_attachment| %>
                      <li><%= link_to("Created on " << has_attachment.created_at.to_formatted_s(:short), has_attachment) %></li>
                    <% end %>
                  </ol>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% unless @photographs.any? %>
  <p class="center">No photos to show!</p>
<% end %>

<%= render 'new' %>