config/routes.rb
Jogger::Application.routes.draw do
  devise_for :people

  root "home#index"

  post 'journals/:journal_id/entries/new' => 'entries#create'
  post 'journals/:journal_id/entries/:id' => 'entries#show'

  get 'journals/:has_taggables_id/entries/tags/:tag' => 'entries#by_tag', as: "entry_tag_search"
  get 'tasks/tags/:tag' => 'tasks#by_tag', as: "task_tag_search"

  resources :journals do
    resources :entries
  end

  resources :tasks
  
  resources :tags

  resources :uploads

  resources :audio_clips
  resources :video_clips
  resources :photographs

end

app/models/audio_clip.rb
class AudioClip < Memory
  
  def folder; "audio_clip"; end
end

app/models/carer.rb
class Carer < Person
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :person

  validates_presence_of :body
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :favourable, polymorphic: true
  belongs_to :person
end

app/models/file_upload.rb
class FileUpload < ActiveRecord::Base

  # Accepts ActionDispatch::Http::UploadedFile
  def self.create_from_params(upload)
    new.tap do |file|
      file.name = "#{hashing}#{File.extname(upload.original_filename)}"
      file.path = "/uploads/memories/#{file.name}"
      file.size = upload.tempfile.size

      file.save

      File.open(
        Rails.root.join('public', 'uploads', 'memories', file.name), 'wb'
      ) do |save_file| 
        save_file.write(upload.read)
      end
    end
  end

  private

    def self.hashing
      Digest::MD5.hexdigest("#{Time.now}")
    end

end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :entries, class_name: "JournalEntry"
  belongs_to :person

  def self.find_by_tag_title(title)
    joins(:tags).where("tags.title = ?", title)
  end
end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  belongs_to :journal
  
  has_many :attaches_memories, as: :has_attachment
  has_many :memories, through: :attaches_memories, source_type: "Memory"
  
  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  validates_presence_of :body

  def self.find_by_tag(title)
    joins(:tags).where("tags.title = ?", title)
  end

  def taggable
    journal
  end

  def attach(memory)
    AttachesMemory.create(has_attachment: self, memory: memory)
  end
end

app/models/memory.rb
class Memory < ActiveRecord::Base
  has_many :attaches_memories, as: :memory

  belongs_to :file, class_name: "FileUpload"
  has_many :comments, as: :commentable
  has_many :favourites, as: :favourable

  def hosted_externally?
    not uploaded
  end

  def tag
    return :audio_tag if self.class.name == "AudioClip"
    return :video_tag if self.class.name == "VideoClip"
    return :image_tag if self.class.name == "Photograph"
  end

  def file_path
    "/memories/#{folder}/#{filename}"
  end

  def attached_to(type)
    attaches_memories.where("has_attachment_type = ?", String(type).camelize).map {|am| am.has_attachment }
  end

  def self.where_attached_to(model)
    AttachesMemory.where(has_attachment: model)
  end

  def delete
    File.delete(Rails.root.join("public", "uploads", "memories", file.name))
    super
  end

  def folder; "memory"; end
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :memories
  has_many :favourites

  def self.types
    ["User", "Carer"]
  end

  def is? a_type
    type.downcase == String(a_type).downcase
  end
end

app/models/photograph.rb
class Photograph < Memory

  def folder; "photograph"; end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :person
  has_many :tasks
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings

  validates_presence_of :title
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base

  belongs_to :taggable, polymorphic: true
  belongs_to :tag

  def self.parse(tags)
    tags.strip.split(",").map {|t| new(tag: Tag.find_or_create_by(title: t)) }
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  has_many :attaches_memories, as: :has_attachment
  has_many :memories, through: :attaches_memories, source_type: "Memory"

  validates_presence_of :details

  def self.find_by_tag(title)
    joins(:tags).where("tags.title = ?", title)
  end

  def attach_many(ids)
    AttachesMemory.attach_to(self, ids)
  end

  def attach(memory)
    AttachesMemory.find_or_create_by(has_attachment: self, memory: memory)
  end
end

app/models/user.rb
class User < Person
  has_many :journals, foreign_key: :person_id
  has_many :journal_entries
  has_many :tasks
  has_many :audio_clips, foreign_key: :person_id
  has_many :video_clips, foreign_key: :person_id
  has_many :photographs, foreign_key: :person_id
end

app/models/video_clip.rb
class VideoClip < Memory

  def folder; "video_clip"; end
end

app/controllers/journal_controller.rb
class JournalController < ApplicationController
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController

  def index
    @journals = current_person.journals
  end

  def show
    @journal = current_person.journals.find(params[:id])
  end

  def new
    @journal = current_person.journals.new
  end

  def create
    @journal = current_person.journals.new(journal_params)
    if @journal.save
      flash[:notice] = "Successfully created a new Journal"
      redirect_to @journal
    else
      flash[:error] = "There were some problems creating your new Journal"
      render :new
    end
  end

  def update
    @journal = current_person.journals.find(params[:id])
    @journal.update_attributes(journal_params)
    if @journal.save
      flash[:notice] = "Successfully updated your Journal"
      redirect_to @journal
    else
      flash[:error] = "There were some problems updating your Journal"
      render :show
    end
  end

  private

    def journal_params
      params.require(:journal).permit(:title)
    end

end

app/helpers/audio_helper.rb
module AudioHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journal_helper.rb
module JournalHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_complete_btn_class(complete)
    "btn " << (complete ? "btn-default active" : "btn-success")
  end
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/journals/_overview.html.erb
<div class="panel panel-default panel-flat">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= glyphicon("list-alt") %> Journals
      <span class="right">
        <%= link_to(glyphicon("plus") << " New Journal", new_journal_path) %>
      </span>
    </h3>
  </div>

  <% unless user.journals.any? %>
    <div class="panel-body">
      <p class="reading center">No Journals! Why not create one by clicking the "New" button and start writing.</p>
    </div>
  <% end %>

  <% if user.journals.any? %>
    <table class="table table-striped">
      <% user.journals.each do |journal| %>
        <tr>
          <td>
            <%= glyphicon("book") %>
            <%= link_to(journal.title, journal) %>

            <span class="right">
              <%= link_to(glyphicon("plus") << " New Entry", new_journal_entry_path(journal), class: "btn btn-warning btn-sm") %>
            </span>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>

</div>

app/views/journals/index.html.erb
<%= render 'overview', user: current_person %>

app/views/journals/new.html.erb
<h3><span class="glyphicon glyphicon-list-alt"></span> New Journal</h3>

<div class="panel panel-flat">
  <div class="panel-body">
    <%= form_for(@journal, html: { class: "form-inline" }) do |f| %>
      <%= f.label(:title) %>
      
      <div class="input-group">
        <%= f.text_field(:title, class: "form-control") %>

        <span class="input-group-btn">
          <%= f.submit("Create", class: "btn btn-primary") %> 
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/journals/show.html.erb
<h3 class="center">
  <%= @journal.title %>
</h3>

<%= render 'entries/index', entries: @journal.entries %>

<%= render 'entries/new', journal: @journal %>